[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#427b58"
[icons]
icons = "awesome"
[icons.overrides]
backlight_empty = " 🌑 "
backlight_partial1 = " 🌘 "
backlight_partial2 = " 🌗 "
backlight_partial3 = " 🌖 "
backlight_full = " 🌕 "
music = " \uf001 "
music_play = " \uf04b "
music_pause = " \uf04c "
music_next = " \uf061 "
music_prev = " \uf060 "
cogs = " \uf085 "
memory_mem = " \uf2db "
memory_swap = " \uf0a0} "
cpu = " \uf0e4 "
bat_half = " \uf242  "
bat_full = " \uf240  "
bat_charging = " \uf1e6 "
bat_discharging = " \uf242 "
bat_quarter = " \uf243  "
bat_three_quarters = " \uf241  "
volume_full = " \uf028 "
volume_half = " \uf027 "
volume_empty = " \uf026 "
volume_muted = "\uf00d"
thermometer = " \uf2c8 "
uptime = " \uf017 "

[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "custom"
interval = 600
command = "~/.local/bin/updates"

[[block]]
block = "music"
player = "mpd"
buttons = ["prev", "play", "next"]

[[block]]
block = "cpu"
format = "{utilization}% {frequency}GHz {barchart}"
interval = 1

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"

[[block]]
block = "uptime"

[[block]]
block = "sound"

#[[block]]
#block = "backlight"

#[[block]]
#block = "battery"
#interval = 1
#format = "{percentage}% {time}"
#device = "CMB1"
